/**
 * 合约地址常量
 * 从 @bsc-trading/contracts 包导入
 */

// 从 SDK contracts 包导入所有合约地址
export {
  ZERO_ADDRESS,
  WBNB_ADDRESS,
  PANCAKESWAP_CONTRACTS,
  FOUR_MEME_CONTRACTS,
  FLAP_CONTRACTS,
  LUNA_CONTRACTS,
  TOKEN_ADDRESSES,
  PROTOCOLS,
  getProtocolContracts,
  getTokenAddress,
  isZeroAddress,
  type Protocol,
  type ProtocolConfig,
} from '@bsc-trading/contracts';

// 为了向后兼容，提供旧的命名
import {
  PANCAKESWAP_CONTRACTS,
  FOUR_MEME_CONTRACTS,
  FLAP_CONTRACTS,
  LUNA_CONTRACTS,
  WBNB_ADDRESS,
  TOKEN_ADDRESSES as SDK_TOKEN_ADDRESSES,
} from '@bsc-trading/contracts';

/**
 * PancakeSwap 合约地址（适配旧命名）
 */
export const PANCAKE_CONTRACTS = {
  ROUTER: PANCAKESWAP_CONTRACTS.ROUTER_V2,
  FACTORY: PANCAKESWAP_CONTRACTS.FACTORY_V2,
  SMART_ROUTER: PANCAKESWAP_CONTRACTS.ROUTER_V3,
  V3_FACTORY: PANCAKESWAP_CONTRACTS.FACTORY_V3,
  V3_QUOTER: PANCAKESWAP_CONTRACTS.QUOTER_V3,
} as const;

/**
 * 统一的合约地址对象（向后兼容）
 */
export const CONTRACTS = {
  // PancakeSwap
  PANCAKE_ROUTER: PANCAKE_CONTRACTS.ROUTER,
  PANCAKE_FACTORY: PANCAKE_CONTRACTS.FACTORY,
  PANCAKE_SMART_ROUTER: PANCAKE_CONTRACTS.SMART_ROUTER,
  PANCAKE_V3_FACTORY: PANCAKE_CONTRACTS.V3_FACTORY,
  PANCAKE_V3_QUOTER: PANCAKE_CONTRACTS.V3_QUOTER,

  // 代币地址
  WBNB: WBNB_ADDRESS,
  CAKE: SDK_TOKEN_ADDRESSES.CAKE,
  ASTER: SDK_TOKEN_ADDRESSES.ASTER,
  USDT: SDK_TOKEN_ADDRESSES.USDT,
  USDC: SDK_TOKEN_ADDRESSES.USDC,
  BUSD: SDK_TOKEN_ADDRESSES.BUSD,
  USD1: SDK_TOKEN_ADDRESSES.USD1,
  UNITED_STABLES_U: SDK_TOKEN_ADDRESSES.UNITED_STABLES_U,
  USAT: SDK_TOKEN_ADDRESSES.USAT,
  KGST: SDK_TOKEN_ADDRESSES.KGST,
  lisUSD: SDK_TOKEN_ADDRESSES.lisUSD,

  // Four.meme 合约
  FOUR_TOKEN_MANAGER_V2: FOUR_MEME_CONTRACTS.TOKEN_MANAGER_V2,
  FOUR_HELPER_V3: FOUR_MEME_CONTRACTS.TOKEN_MANAGER_HELPER,

  // Flap Portal 合约
  FLAP_PORTAL: FLAP_CONTRACTS.PORTAL,

  // Luna.fun Launchpad
  LUNA_FUN_LAUNCHPAD: LUNA_CONTRACTS.LAUNCHPAD,
} as const;
